import 'package:flutter/material.dart';
void main(){
  runApp(
    MaterialApp(
      home:Scaffold(
        backgroundColor:Colors.black,
        appBar:AppBar(title:Text("student profile")),
        body:Center(
          child:Container(
            height:300,
            width:300,
            color:Colors.white,
            child:Column(
              children:[
                Container(
                  height:100,
                  width:100,
                  color:Colors.black,
                ),
                SizedBox(height:25),
                Image.network(
                  "https://vishnucollege.photos/200/300"
                  height:100,
                  width:100,
                ),
                SizedBox(height:25),
                Text(
                  "Name:Nikhil varma",
                  style:TextStyle(
                    fontSize:20,
                    fontWeight:FontWeight.bold,
                  ),
                ),
                SizedBox(height:25),
                Text(
                  "rollno:24pa1a05e4",
                  style:TextStyle(
                    fontSize:20,
                  ),
                ),
                SizedBox(height:25),
                Text(
                  "branch:cse",
                  style:TextStyle(
                    fontSize:20,
                  ),
                ),
                SizedBox(height:25),
                Container(
                  height:100,
                  width:100,
                  color:Colors.black,
                  child:Row(
                    mainAxisAlignment:MainAxisAlignment.center,
                    children:[
                      Text("8233233445"),
                    ],
                  ),
                ),
                Container(
                  height:100,
                  width:100,
                  color:Colors.black,
                  child:Row(
                    mainAxisAlignment:MainAxisAlignment.center,
                    children:[
                      Text("nikhilvarmamandapati@gmail.com"),
                    ]
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    ),    
  );
}  